export const testData = [
  {
    type: 'input',
    field: 'lwk5w2fc0eub',
    title: '输入框',
    info: '',
    _fc_drag_tag: 'input',
    hidden: false,
    display: true,
    value: null,
  },
  {
    type: 'datePicker',
    field: 'dsk5w2fcs3y9',
    title: '日期选择器',
    info: '',
    _fc_drag_tag: 'datePicker',
    hidden: false,
    display: true,
    value: null,
  },
  {
    type: 'radio',
    field: 'mun5w2fc0laa',
    title: '单选框',
    info: '',
    effect: {
      fetch: '',
    },
    options: [
      {
        value: '1',
        label: '选项1',
      },
      {
        value: '2',
        label: '选项2',
      },
    ],
    _fc_drag_tag: 'radio',
    hidden: false,
    display: true,
    value: null,
  },
  {
    type: 'switch',
    field: 'y5i5w2fc0shr',
    title: '开关',
    info: '',
    _fc_drag_tag: 'switch',
    hidden: false,
    display: true,
    value: null,
  },
  {
    type: 'switch',
    field: 'eq75w2fcrw3g',
    title: '开关',
    info: '',
    _fc_drag_tag: 'switch',
    hidden: false,
    display: true,
    value: null,
  },
  {
    type: 'datePicker',
    field: 'dsk5w2fcs3y9',
    title: '日期选择器',
    info: '',
    _fc_drag_tag: 'datePicker',
    hidden: false,
    display: true,
    value: null,
  },
  {
    type: 'datePicker',
    field: 'dsk5w2fcs3y9',
    title: '日期选择器',
    info: '',
    _fc_drag_tag: 'datePicker',
    hidden: false,
    display: true,
    value: null,
  },
]
